### Numpy Linear Algebra

#### solutions to Matrix equations

A system of linear equations can be converted to a matrix equation and solved with numpy

In [17]:
import numpy as np

a = np.array([[3,-1], [-1,-1]])

b = np.array([[2],[6]])

print(a)
print(b)

np.linalg.solve(a,b)
#np.linalg.lstsq(a,b)

[[ 3 -1]
 [-1 -1]]
[[2]
 [6]]


array([[-1.],
       [-5.]])

#### Matrix transformations

In [25]:
import numpy as np

a = np.arange(4).reshape(2,2)

print(a)
print(a.transpose()) # a.transpose creates a new array, does not change a
print(a)

print(a.trace()) # sum the diagonal

print(np.linalg.inv(a)) # find the inverse of a matrix


[[0 1]
 [2 3]]
[[0 2]
 [1 3]]
[[0 1]
 [2 3]]
3
[[-1.5  0.5]
 [ 1.   0. ]]


#### Matrix values

#### Eigenvectors and Eigenvalues

In [27]:
import numpy as np

w, v = np.linalg.eig(np.array([[1, -1], [1, 1]]))
w; v


array([[ 0.70710678+0.j        ,  0.70710678-0.j        ],
       [ 0.00000000-0.70710678j,  0.00000000+0.70710678j]])

#### Decompositions

##### SVD

Singular Value Decompositions (SVD) are very useful.  They are related to principle component analysis (PCA).  They can be used in data compression, pattern recognition, and 

The numpy.linalg.lstsq uses SVD to find solutions

In [31]:
import numpy as np

testArray = np.array([[3, 2, 2], [2, 3, -2]])

plotData = 

print(testArray)

# Compute the SVD
np.linalg.svd(testArray)

[[ 3  2  2]
 [ 2  3 -2]]


(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([ 5.,  3.]),
 array([[ -7.07106781e-01,  -7.07106781e-01,  -5.55111512e-17],
        [ -2.35702260e-01,   2.35702260e-01,  -9.42809042e-01],
        [ -6.66666667e-01,   6.66666667e-01,   3.33333333e-01]]))

##### QR Decompostion

##### Cholesky Decompostion

Scipy also has a linalg module that includes all the numpy linalg features with the addition of a few other methods.  These will be discussed when we work more with the scipy package.